permalink: /:year/:month/:day/:title.html
paginate: 15
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
 # coderay:
 #   coderay_line_numbers:  nil

# 作者信息
author: 
  name: Bowei Shen
  email: shenbowei1991@126.com
  github: http://github.com/shenbowei

# 站点信息
title: 知其然知其所以然
description: My personal blog
url: https://blog.shenbowei.tech
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/avatar.jpg
favicon: /public/img/avatar.jpg

# google analytics 设置
ga:
  id: UA-91776373-1
  url: shenbowei.github.io

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
#cates:
#  - 读书

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  
# comment
home: http://shenbowei.github.io
api: http://api.shenbowei.tech/myapi
img: http://blog.shenbowei.tech/public/img/emoji
  