permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
 # coderay:
 #   coderay_line_numbers:  nil

# 作者信息
author: 
  name: Bowei Shen
  email: shenbowei1991@126.com
  github: http://github.com/shenbowei

# 站点信息
title: 知其然知其所以然
description: My personal blog
url: https://shenbowei.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/avatar.jpg
favicon: /public/img/avatar.jpg


# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
#cates:
#  - 读书

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档